
set(CMAKE_SYSTEM_PROCESSOR "wasm32" CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_NAME "Emscripten" CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_CROSSCOMPILING TRUE)
set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
set(UNIX 1)
set(SYSTRIPLET "${CMAKE_SYSTEM_PROCESSOR}-unknown-emscripten" CACHE STRING "" FORCE)
add_compile_definitions(_LIBCPP_ENABLE_EXPERIMENTAL)
set(TOOLCHAIN_PATH "/" CACHE PATH "Path to toolchain native sysroot")
SET(TARGET_SYSROOT_PATH "/" CACHE PATH "Path to toolchain target sysroot")

find_program(EMCC NAMES emcc REQUIRED)
find_program(EMPP NAMES em++ REQUIRED)
find_program(EMAR NAMES emar REQUIRED)
find_program(EMRANLIB NAMES emranlib REQUIRED)
		
SET(CMAKE_FORCE_C_COMPILER ${EMCC})
SET(CMAKE_FORCE_CXX_COMPILER ${EMPP})
SET(CMAKE_C_COMPILER ${CMAKE_FORCE_C_COMPILER})
SET(CMAKE_CXX_COMPILER ${CMAKE_FORCE_CXX_COMPILER})
set(CMAKE_CXX_COMPILER_AR ${EMAR})
set(CMAKE_AR ${EMAR})
set(CMAKE_CXX_COMPILER_RANLIB ${EMRANLIB})
set(CMAKE_RANLIB ${EMRANLIB})

add_compile_options( -mbulk-memory )
add_compile_options(  -sUSE_BOOST_HEADERS=1)

add_link_options( -sALLOW_MEMORY_GROWTH -sMAXIMUM_MEMORY=4294901760 )

set(EMSCRIPTEN_ENV "web")
